version: '3.8'

services:
  smhmwebapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: smhm_web_api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__SmartHomeDbContext=Host=db;Database=SmartHomeDb;Username=postgres;Password=140779
      
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 140779
      POSTGRES_DB: smhm_database
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db_postgresql_container

volumes:
  db_data: